name: test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5
      - run: pnpm i --frozen-lockfile
      - run: pnpm ts
      - run: pnpm test
      - run: pnpm build
